[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/remoteEntry.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/style.css"
  [headers.values]
    Access-Control-Allow-Origin = "*"
